entries:
  ru:
    f:
      - title: Быстрый старт разработчика
        url: "200_basic.html"
        sf:
          - title: Сборка образа
            url: "201_build.html"
          - title: Подготовка кластера
            url: "210_cluster.html"
          - title: Деплой приложения
            url: "220_deploy.html"
          - title: Ускорение сборки
            url: "230_optimize.html"
          - title: Конфигурирование инфраструктуры в виде кода
            url: "240_iac.html"

      - title: Полноценные приложения
        url: "300_basic.html"
        sf:
          - title: Организация локальной разработки
            url: "301_local.html"
          - title: Отладка кода инфраструктуры
            url: "301_debug_iac.html"
          - title: Генерируем и раздаём ассеты
            url: "302_assets.html"
          - title: Statefull-приложение
            url: "304_statefull.html"
          - title: Работа с файлами
            url: "310_files.html"
          - title: Работа с электронной почтой
            url: "320_email.html"
          - title: Подключаем Managed Redis
            url: "330_redis.html"
          - title: Подключаем Managed PostgreSQL
            url: "340_database.html"

      - title: Работа с инфраструктурой
        url: "500_basic.html"
        sf:
          - title: Построение CI-процесса
            url: "510_ci.html"
          - title: Юнит-тесты и Линтеры
            url: "520_unittesting.html"
          - title: Несколько приложений в одном репозитории
            url: "530_multipleapps.html"
          - title: Динамические окружения
            url: "540_dynamicenvs.html"
