app:
  isDebug:
    _default: "true"
    production: "false"
    testing: "true"
  postgresql:
    login:
      _default: guide-username
    host:
      _default: postgresql
    port:
      _default: 5432
    db:
      _default: guided-database

postgresql:
  postgresqlDatabase: guided-database
  postgresqlUsername: guide-username
  postgresqlHost: postgresql
  imageTag: "12"
  fullnameOverride: postgresql
  nameOverride: postgresql
  persistence:
    storageClass: "local-storage"
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    annotations: {}