output: web

site_title: werf
site_urls:
  ru: https://ru.werf.io
  en: https://werf.io

highlighter: rouge

plugins:
  - jekyll-assets
  - jekyll-remote-plantuml

assets:
  cdn:
    baseurl: true

plantuml:
  type: svg
  assets: assets/images/plantuml_cache/

markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge
