output: web

site_title: werf
site_urls:
  ru: https://ru.werf.io
  en: https://werf.io
editlink: "https://github.com/werf/werf-guides/edit/master"

highlighter: rouge

plugins:
  - jekyll-assets
  - jekyll_remote_plantuml_plugin
  - jekyll_include_plugin

assets:
  cdn:
    baseurl: true

plantuml:
  format: svg
  save_images_locally: true
  cache_dir: assets/images/plantuml_cache

markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge
