output: web

site_title: werf
site_urls:
  ru: https://ru.werf.io
  en: https://werf.io
editlink: "https://github.com/werf/website/edit/main"
canonical_url_prefix: /documentation/v2

social_links:
  ru:
    twitter: https://twitter.com/werf_io
    telegram: https://t.me/werf_ru
    slack_1: https://slack.cncf.io/
    slack_2: https://cloud-native.slack.com/messages/CHY2THYUU
  en:
    telegram: https://t.me/werf_io
    twitter: https://twitter.com/werf_io
    slack_1: https://slack.cncf.io/
    slack_2: https://cloud-native.slack.com/messages/CHY2THYUU

highlighter: rouge

plugins:
  - jekyll-assets
  - jekyll_remote_plantuml_plugin
  - jekyll_include_plugin
  - jekyll-include-cache

plantuml:
  format: svg
  save_images_locally: true
  cache_dir: assets/images/plantuml_cache

markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge

timezone: Europe/Moscow
