version: "3.9"

services:
  # en:
  #   image: $WERF_JEKYLL_BASE_DOCKER_IMAGE_NAME
  #   working_dir: "/srv/jekyll-data"
  #   environment:
  #     JEKYLL_ENV: "dev"
  #   command: bash -c "
  #     chmod -R o+w /srv/jekyll-data/ &&
  #     jekyll serve -t --disable-disk-cache --config _config.yml,_config_dev.yml,_config_en.yml --baseurl /guides --destination /tmp/_site -P 80"
  #   volumes:
  #     - "./:/srv/jekyll-data/"
  ru:
    image: $WERF_JEKYLL_BASE_DOCKER_IMAGE_NAME
    working_dir: "/srv/jekyll-data"
    environment:
      JEKYLL_ENV: "dev"
    command: bash -c "
      chmod -R o+w /srv/jekyll-data/ &&
      jekyll serve -t --disable-disk-cache --config _config.yml,_config_dev.yml,_config_ru.yml --baseurl /guides --destination /tmp/_site -P 80"
    volumes:
      - "./:/srv/jekyll-data/"
    restart: always
    # depends_on:
    #   - en

  front:
    image: nginx:latest
    volumes:
      - ".werf/nginx-dev.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - ru
      # - en
