apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp
spec:
  selector:
    matchLabels:
      app: basicapp
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: ["java","-jar","/app/demo.jar"]
        image: {{ .Values.werf.image.basicapp }}
        workingDir: /app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: "SQLITE_FILE"
          value: "app.db"
        - name: "S3_ENDPOINT"
          value: "s3.selcdn.ru"
        - name: "S3_PORT"
          value: "9000"
        - name: "S3_SSL"
          value: "true"
        - name: "S3_ZONE"
          value: "ru-1a"
        - name: "S3_BUCKET"
          value: "test-container"
        - name: "S3_ACCESS_KEY"
          value: "47951_Clarisse"
        - name: "S3_SECRET_KEY"
          value: "i{z^e9WX"