apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp
spec:
  selector:
    matchLabels:
      app: basicapp
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: ["node","/app/app.js"]
        image: {{ tuple "basicapp" . | werf_image}}
        workingDir: /app
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: "SQLITE_FILE"
          value: "app.db"
        - name: "MAILGUN_APIKEY"
          value: "key-edec40bdee01d7c75cc25aeb1c09145e"
        - name: "MAILGUN_DOMAIN"
          value: "sandboxdad71610c342445aa4ab9bd5fe448eaf.mailgun.org"
        - name: "MAILGUN_HOST"
          value: "api.eu.mailgun.net"
        - name: "REPORT_RECIEVER"
          value: "maicatus@gmail.com"
