company_name: Флант
company_url: https://flant.ru
url: https://ru.werf.io
site_lang: ru
baseurl: /applications_guide_ru
docsurl: https://ru.werf.io

breadcrumbs:
  hometext: "Начало"

defaults:
  - scope:
      path: "nodejs"
      type: "pages"
    values:
      lang: ru
      sidebar: applications_guide
      guide_code: nodejs
      toc: false
      label_ci: GitLab
      label_framework: NodeJS
  - scope:
      path: "java_springboot"
      type: "pages"
    values:
      lang: ru
      sidebar: applications_guide
      guide_code: java_springboot
      toc: false
      label_ci: GitLab
      label_framework: Springboot
  - scope:
      path: "python_django"
      type: "pages"
    values:
      lang: ru
      sidebar: applications_guide
      guide_code: python_django
      toc: false
      label_ci: GitLab
      label_framework: Django
  - scope:
      path: "rails"
      type: "pages"
    values:
      lang: ru
      sidebar: applications_guide
      guide_code: rails
      toc: false
      label_ci: GitLab
      label_framework: Rails