apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp
spec:
  selector:
    matchLabels:
      app: basicapp
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      initContainers:
      - name: basicapp-migrations
        command: [ "/bin/bash", "-ec", "until bundle exec rails db:migrate ; do echo ; echo Waiting for database startup ... ; sleep 1 ; done" ]
        image: {{ .Values.werf.image.basicapp }}
        workingDir: /app
      containers:
      - name: basicapp
        command: [ "/bin/bash", "-ec", "bundle exec puma" ]
        image: {{ .Values.werf.image.basicapp }}
        workingDir: /app
        ports:
        - containerPort: 3000
          protocol: TCP
