entries:
  ru:
    f:
      - title: Первые шаги
        url: "100_basic.html"
        sf:
          - title: Сборка образа
            url: "100_basic/10_build.html"
          - title: Подготовка окружения
            url: "100_basic/20_cluster.html"
          - title: Деплой приложения
            url: "100_basic/30_deploy.html"
          - title: Внесение изменений
            url: "100_basic/35_deploy_changes.html"
          - title: Необходимо знать
            url: "100_basic/40_must_haves.html"

      - title: Реалистичные приложения
        url: "200_real_apps.html"
        sf:
          - title: Логирование
            url: "200_real_apps/25_logging.html"
          - title: Генерируем и раздаём ассеты
            url: "200_real_apps/30_assets.html"
          - title: Работа с файлами
            url: "200_real_apps/50_files.html"
          - title: Работа с электронной почтой
            url: "200_real_apps/60_email.html"
          - title: Подключаем внешний PostgreSQL
            url: "200_real_apps/80_database.html"
          - title: Stateful-приложение
            url: "200_real_apps/90_stateful.html"

      - title: Организация разработки
        url: "300_dev_process.html"
        sf:
          - title: Локальная разработка
            url: "300_dev_process/10_local.html"
          - title: Нелокальная разработка
            url: "300_dev_process/20_nonlocal.html"

      - title: Повышение качества разработки
        url: "400_dev_experience.html"
        sf:
          - title: Ускорение доставки
            url: "400_dev_experience/10_optimize.html"
          - title: Упрощение отладки сборки
            url: "400_dev_experience/20_debug.html"
          - title: Отладка проблем в кластере
            url: "400_dev_experience/30_debug_iac.html"

      - title: Работа с инфраструктурой
        url: "400_infra.html"
        sf:
          - title: Построение CI-процесса
            url: "400_infra/10_ci.html"
          - title: Юнит-тесты и Линтеры
            url: "400_infra/20_unittesting.html"
          - title: Динамические окружения
            url: "400_infra/40_dynamicenvs.html"
