stages:
- build
- deploy
- cleanup

before_script:
  - type multiwerf && source <(multiwerf use 1.1 stable)
  - type werf && source <(werf ci-env gitlab --verbose)

.base_deploy: &base_deploy
  stage: deploy
  script:
    - werf deploy
  dependencies:
    - Build
  tags:
    - werf

Build:
  stage: build
  script:
    - werf build-and-publish
  tags:
    - werf

Deploy to staging:
  extends: .base_deploy
  environment:
    name: staging
  only:
    - merge_requests
  when: manual

Deploy to production:
  extends: .base_deploy
  environment:
    name: production
  only:
    - master

Cleanup:
  stage: cleanup
  script:
    - type multiwerf && source <(multiwerf use 1.1 stable)
    - type werf && source <(werf ci-env gitlab --tagging-strategy tag-or-branch --verbose)
    - docker login -u nobody -p ${WERF_IMAGES_CLEANUP_PASSWORD} ${WERF_IMAGES_REPO}
    - werf cleanup --stages-storage :local
  only:
    - schedules