---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      initContainers:
        - name: wait-redis
          image: alpine:3.6
          command: ['/bin/sh', '-c', 'while ! getent ahostsv4 {{ pluck .Values.global.env .Values.redis.host | first | default .Values.redis.host._default }}; do sleep 1; done']
      containers:
      - name: basicapp
        command: ["node","/app/app.js"]
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: "DEBUG"
          value: "{{ pluck .Values.global.env .Values.app.isDebug | first | default .Values.app.isDebug._default }}"
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password | quote }}
        - name: REDIS_PORT
          value: {{ pluck .Values.global.env .Values.redis._port | first | default .Values.redis._port._default | quote }}
        - name: REDIS_HOST
          value: {{ pluck .Values.global.env .Values.redis.host | first | default .Values.redis.host._default | quote }}
        - name: SESSION_TTL
          value: {{ pluck .Values.global.env .Values.app.redis.session_ttl | first | default .Values.app.redis.session_ttl._default | quote }}
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}