options:
  - name: "usage"
    group: "1"
    values:
      - "ci"
      - "local-dev"

  - name: "version"
    group: "2"
    values:
      - "1.2"
      - "1.1"
  - name: "channel"
    group: "2"
    values:
      - "rock-solid"
      - "stable"
      - "early-access"
      - "beta"
      - "alpha"
  - name: "build-backend"
    group: "2"
    values:
      - "docker"
      - "buildah"
  - name: "host-os"
    group: "2"
    values:
      - "linux"
      - "macos"
      - "windows"
  - name: "arch"
    group: "2"
    values:
      - "amd64"
      - "arm64"
  # TODO:
  # - name: "container-registry"
  #   group: "2"

  - name: "ci"
    group: "3"
    values:
      - "github-actions"
      - "gitlab-ci-cd"
      - "other-ci-cd-system"
  - name: "runner-type"
    group: "3"
    values:
      - "host-runner"
      - "docker-runner"
      - "kubernetes-runner"
  - name: "runner-os"
    group: "3"
    values:
      - "linux"
      - "macos"
      - "windows"
  - name: "werf-image-distro"
    group: "3"
    values:
      - alpine
      - ubuntu
      - fedora

  - name: "project-type"
    group: "4"
    values:
      - "simple"
      - "singlerepo"
      - "monorepo"
      - "multirepo"

combinations:

  # local
  - tabs:
      - name: "setup"
        partial: "dev/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "local-dev"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "host-os"
        value: "linux"
      - name: "build-backend"
        value: "docker"
  - tabs:
      - name: "setup"
        partial: "dev/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "local-dev"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "host-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
  - tabs:
      - name: "setup"
        partial: "dev/macos/docker.md.liquid"
    options:
      - name: "usage"
        value: "local-dev"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "host-os"
        value: "macos"
      - name: "build-backend"
        value: "docker"
  - tabs:
      - name: "setup"
        partial: "dev/windows/docker.md.liquid"
    options:
      - name: "usage"
        value: "local-dev"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "host-os"
        value: "windows"
      - name: "build-backend"
        value: "docker"

  # github actions simple
  - tabs:
      - name: "setup"
        partial: "ci/github-actions/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "github-actions"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"

  # gitlab ci cd simple
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/simple/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "docker"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/simple/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "docker-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/simple/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "kubernetes-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"

  # gitlab-ci-cd best-practice
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/best-practice/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "best-practice"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/best-practice/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "docker"
      - name: "project-type"
        value: "best-practice"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/best-practice/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "docker-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "best-practice"
  - tabs:
      - name: "setup"
        partial: "ci/gitlab-ci-cd/best-practice/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlab-ci-cd"
      - name: "runner-type"
        value: "kubernetes-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "best-practice"

  # other ci cd system simple
  - tabs:
      - name: "setup"
        partial: "ci/other-ci-cd-system/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "other-ci-cd-system"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/other-ci-cd-system/simple/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "other-ci-cd-system"
      - name: "runner-type"
        value: "host-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "docker"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/other-ci-cd-system/simple/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "other-ci-cd-system"
      - name: "runner-type"
        value: "docker-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"
  - tabs:
      - name: "setup"
        partial: "ci/other-ci-cd-system/simple/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: ".*"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "other-ci-cd-system"
      - name: "runner-type"
        value: "kubernetes-runner"
      - name: "runner-os"
        value: "linux"
      - name: "build-backend"
        value: "buildah"
      - name: "werf-image-distro"
        value: ".*"
      - name: "project-type"
        value: "simple"