options:
  - name: "usage"
    group: "1"
    values:
      - "ci"
      - "localDev"

  - name: "version"
    group: "2"
    values:
      - "1.2"
  - name: "channel"
    group: "2"
    values:
      - "rockSolid"
      - "stable"
      - "earlyAccess"
      - "beta"
      - "alpha"
  - name: "buildBackend"
    group: "2"
    values:
      - "docker"
      - "buildah"
  # TODO:
  # - name: "containerRegistry"
  #   group: "2"

  - name: "ci"
    group: "3"
    values:
      - "githubActions"
      - "gitlabCiCd"
      - "otherCiCdSystem"
  - name: "runnerType"
    group: "3"
    values:
      - "hostRunner"
      - "dockerRunner"
      - "kubernetesRunner"
  - name: "os"
    group: "3"
    values:
      - "linux"
      - "macos"
      - "windows"
  - name: "werfImageDistro"
    group: "3"
    values:
      - alpine
      - ubuntu
      - fedora

  - name: "projectType"
    group: "4"
    values:
      - "simple"
      - "singlerepo"
      - "monorepo"
      - "multirepo"

combinations:

  # local
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/dev/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "localDev"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "docker"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/dev/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "localDev"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/dev/macos/docker.md.liquid"
    options:
      - name: "usage"
        value: "localDev"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "os"
        value: "macos"
      - name: "buildBackend"
        value: "docker"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/dev/windows/docker.md.liquid"
    options:
      - name: "usage"
        value: "localDev"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "os"
        value: "windows"
      - name: "buildBackend"
        value: "docker"

  # github actions simple
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/github-actions/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "githubActions"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"

  # gitlab ci cd simple
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/simple/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "docker"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/simple/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "dockerRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/simple/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "kubernetesRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"

  # gitlabCiCd singlerepo
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/singlerepo/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "singlerepo"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/singlerepo/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "docker"
      - name: "projectType"
        value: "singlerepo"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/singlerepo/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "dockerRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "singlerepo"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/gitlab-ci-cd/singlerepo/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "gitlabCiCd"
      - name: "runnerType"
        value: "kubernetesRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "singlerepo"

  # other ci cd system simple
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "otherCiCdSystem"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/docker.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "otherCiCdSystem"
      - name: "runnerType"
        value: "hostRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "docker"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/other-ci-cd-system/simple/docker-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "otherCiCdSystem"
      - name: "runnerType"
        value: "dockerRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"
  - tabs:
      - name: "setup"
        includePath: "/configurator/tab/ci/other-ci-cd-system/simple/kubernetes-runner/linux/buildah.md.liquid"
    options:
      - name: "usage"
        value: "ci"
      - name: "version"
        value: "1.2"
      - name: "channel"
        value: ".*"
      - name: "ci"
        value: "otherCiCdSystem"
      - name: "runnerType"
        value: "kubernetesRunner"
      - name: "os"
        value: "linux"
      - name: "buildBackend"
        value: "buildah"
      - name: "werfImageDistro"
        value: ".*"
      - name: "projectType"
        value: "simple"