app:
  secretEnvs:
    DB_HOST: 100002475edf3caf7f0ad16e82516825d644920931860dfd03d18a223ace3e904a8d
    DB_NAME: 1000cc9bc17cdf9be0d243a175e70c678551fabc2fc565400d4f1d073971d04c4476
    DB_USER: 1000b30937700b0ae942521863c68bf07838d69d21777e3969ed9dae11c80a25aec0
    DB_PASSWD: 1000f3946440168fedd538ad970295a07f1d879ff326cb9bc5dcdc37d3aded7d62a6
    MINIO_ROOT_USER: 10004f7c0096a31188fcf08d72caec935232eba574b5173fec7545cc4e79e46d2dbb
mysql:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10002c1ab8d562a23214595282f55f8e0c84ee494acfe9a6b8b2d42f1e72d89c0325
minio:
  secretEnvs:
    MINIO_ROOT_PASSWORD: 10002c9d8394bab865f6836c0a8440a497242896a8890b96c9d006ce5a677ce7f4a0
