entries:
  ru:
    f:
      - title: Быстрый старт разработчика
        url: "100_basic.html"
        sf:
          - title: Сборка образа
            url: "100_basic/10_build.html"
          - title: Подготовка окружения
            url: "100_basic/20_cluster.html"
          - title: Деплой приложения
            url: "100_basic/30_deploy.html"

      - title: Полноценные приложения
        url: "200_real_apps.html"
        sf:
          - title: Организация локальной разработки
            url: "200_real_apps/10_local.html"
          - title: Отладка кода инфраструктуры
            url: "200_real_apps/20_debug_iac.html"
          - title: Логгирование
            url: "200_real_apps/25_logging.html"
          - title: Генерируем и раздаём ассеты
            url: "200_real_apps/30_assets.html"
          - title: Работа с файлами
            url: "200_real_apps/50_files.html"
          - title: Работа с электронной почтой
            url: "200_real_apps/60_email.html"
          - title: Подключаем Managed PostgreSQL
            url: "200_real_apps/80_database.html"
          - title: Ускорение доставки
            url: "100_basic/40_optimize.html"
          - title: Stateful-приложение
            url: "200_real_apps/90_stateful.html"
          - title: Организация не локальной разработки
            url: "100_basic/50_iac.html"

      - title: Работа с инфраструктурой
        url: "400_infra.html"
        sf:
          - title: Построение CI-процесса
            url: "400_infra/10_ci.html"
          - title: Юнит-тесты и Линтеры
            url: "400_infra/20_unittesting.html"
          - title: Несколько приложений в одном репозитории
            url: "400_infra/30_multipleapps.html"
          - title: Динамические окружения
            url: "400_infra/40_dynamicenvs.html"
