apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  # [<ru>] Имя Ingress-ресурса.
  name: werf-guide-app
spec:
  rules:
  # [<ru>] Домен, запросы на который будут обрабатываться в paths ниже.
  - host: werf-guide-app
    http:
      paths:
      # [<ru>] Запросы с префиксом / (все запросы) перенаправятся на порт 8000 нашего Service.
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werf-guide-app
            port:
              number: 8000
