priorityClassName:
  _default: develop
  production: production-medium
host:
  production: werf.io
  stage: werf.stage.flant.dev
  dev: werf.dev.flant.dev
  _default: werf.test.flant.dev

ingressClassName:
  _default: "nginx"
  production: "standalone-geo"

ingressSecretName:
  _default: wildcard-dev-flant-dev
  test: wildcard-test-flant-dev
  stage: wildcard-stage-flant-dev

resources:
  requests:
    memory:
      _default: 30M
      production: 300M

