name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "Taskfile.yaml"
      - ".github/**"
      - "bin/**"
      - "_data/**"
      - "_config*"
      - "backend/**"
  pull_request:
  repository_dispatch:
    types: ["Lint"]
  workflow_dispatch:

jobs:
  lint:
    uses: werf/common-ci/.github/workflows/lint.yml@chore/ci/lint
    with:
      directories: '["bin/configurator", "backend"]'
      cmd: task -p lint:golangci-lint

  notification:
    name: Notification
    needs: lint
    if: always()
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
